services:
  postgres-db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: restaurantdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data


